name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why do you need it?
